{% if site.google_ads_5 %}
	<div id="bottom_ad_unit" class="googads txf_noads">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Responsive 5 BTF -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2290933460302426"
     data-ad-slot="8023455687"
     data-ad-format="rectangle"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>	
  </div>
{% endif %}
