{% if site.google_ads_9 %}
			<div id="bottom_ad_unit" class="googads txf_noads" style="margin-top:10px;">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-7363809219244122"
     data-ad-slot="3481189687"
     data-ad-format="rectangle"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
			</div>
{% endif %}