{% if site.google_ads_1 %}
<div id="wide_ad_unit" class="googads txf_noads" style="margin-bottom:10px; margin-top: 10px;">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Responsive 1 ATF -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2290933460302426"
     data-ad-slot="6686323280"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
{% endif %}