<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{{ page.title }}</title>
<script type="text/javascript" src="https://www.google.com/jsapi?key=ABQIAAAAJdkGEFTgqxMMkDNcBhIkxRToDxNj1XMoLLLfh-7X858QwysyFBS9ehOLy-x-TNlJBSthVEWT0oTl3Q"></script>
<script language="Javascript" type="text/javascript" charset="utf-8">
//<![CDATA[
    google.load("jquery", "1");
    function OnLoad() {
    }
    google.setOnLoadCallback(OnLoad);
//]]>
</script>
<link rel="icon" href="//d7zeocn4055cf.cloudfront.net/img/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="//d7zeocn4055cf.cloudfront.net/img/favicon.ico" type="image/x-icon">
<link href="//d7zeocn4055cf.cloudfront.net/static/bootstrap-2.3.2/css/style.css" rel="stylesheet">
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script>
window.google_analytics_uacct = "UA-137745-1"
</script>
<style>
.breadcrumb {background-color:#f5f5f5;}
</style>
</HEAD>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="#">{{ site.name }}</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/">Inicio</a></li>
              <li><a href="#about">Archivo</a></li>
              <li><a href="#contact">Contacto</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

